export { HomeView } from './home';
export { ArtView } from './art';
export { ArtCreateView } from './artCreate';
export { ArtistView } from './artist';
export { ArtistsView } from './artists';
export { AuctionView } from './auction';
export { AuctionCreateView } from './auctionCreate';
export { ArtworksView } from './artworks';
export { AnalyticsView } from './analytics';
