export { HomeView } from './home';
export { ArtView } from './art';
export { ArtCreateView } from './artCreate';
export { ArtistView } from './artist';
export { ArtistsView } from './artists';
export { AuctionView } from './auction';
export { AuctionCreateView } from './auctionCreate';
export { ArtworkView } from './artwork';
export { ArtistAlleyView } from './artistAlley';
export { StaticPageView } from './staticPage'
