timeout: 1800s
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/circlepod-web-nfts-app:$REVISION_ID', '.']
  id: 'build-gcr'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/circlepod-web-nfts-app:$REVISION_ID']
  id: 'push-gcr'
  waitFor:
  - 'build-gcr'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'circlepod-web-nfts-app-services', '--image', 'asia.gcr.io/$PROJECT_ID/circlepod-web-nfts-app:$REVISION_ID', '--region', 'asia-east1', '--platform', 'managed', '--memory', '512Mi', '--set-env-vars', 'NODE_ENV=production,HOST=0.0.0.0','--allow-unauthenticated']
  id: 'deploy-gcr'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'services', 'update-traffic', circlepod-web-nfts-app-services', '--to-latest', '--region', 'asia-east1']
  waitFor:
  - 'deploy-gcr'
