import {
  ArweaveTransaction,
  Storefront,
  ArweaveQueryResponse,
} from '@oyster/common';
import {
  createClient,
  RedisClientOptions,
  RedisClientType,
  RedisModules,
  RedisScripts,
} from 'redis';
import moment from 'moment';
import { maybeCDN } from '../utils/cdn';

const ARWEAVE_URL = process.env.NEXT_PUBLIC_ARWEAVE_URL;
const REDIS_URL = process.env.REDIS_URL;
const REDIS_TLS_ENABLED = process.env.REDIS_TLS_ENABLED === 'true';

const fetchdenyListCacheKey = async (): Promise<Array<String>> => {
  const res = await fetch('https://api.holaplex.com', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      jsonrpc: '2.0',
      method: 'getOwnerDenylist',
      params: [],
      id: 1337,
    }),
  });
  // @ts-ignore
  return await res.json();
};

const denyListCacheKey = 'ownerdenyList';
const fetchFromSource = async (
  subdomain: string,
  redisClient: RedisClientType,
): Promise<Storefront | null> => {
  try {
    const response = await fetch(`${ARWEAVE_URL}/graphql`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query: `
            query GetStorefrontTheme($subdomain: String!) {
              transactions(tags:[{ name: "holaplex:metadata:subdomain", values: [$subdomain]}], first: 1) {
                edges {
                  node {
                    id
                    tags {
                      name
                      value
                    }
                  }
                }
              }
            }
          `,
        variables: {
          subdomain,
        },
      }),
    });

    const {
      data: {
        transactions: {
          edges: [{ node }],
        },
      },
    } = (await response.json()) as ArweaveQueryResponse;
    const transaction = node as ArweaveTransaction;

    const values = transaction.tags.reduce((acc: any, tag) => {
      acc[tag.name] = tag.value || null;

      return acc;
    }, {});

    let pubkeydenyList: Array<String> = [];
    try {
      const cachedValue = (await redisClient.get(denyListCacheKey)) || '{}';
      pubkeydenyList = JSON.parse(cachedValue).result || [];

      if (!pubkeydenyList.length) {
        pubkeydenyList = await fetchdenyListCacheKey();
        redisClient.set(
          denyListCacheKey,
          // @ts-ignore
          JSON.stringify(pubkeydenyList),
        );
        redisClient.expire(denyListCacheKey, 300); // cache the entire list for 5 minutes

      }
    } catch (error) {
      console.error('failed to fetch denylist', error);
    }

    if (pubkeydenyList.includes(values['solana:pubkey'])) {
      return null;
    }

    const storefront = {
      subdomain,
      pubkey: values['solana:pubkey'],
      theme: {
        logo: maybeCDN(values['holaplex:theme:logo:url']),
        banner: maybeCDN(values['holaplex:theme:banner:url'] || ''),
        stylesheet: maybeCDN(`${ARWEAVE_URL}/${transaction.id}`),
        color: {
          background: values['holaplex:theme:color:background'],
          primary: values['holaplex:theme:color:primary'],
        },
        font: {
          title: values['holaplex:theme:font:title'],
          text: values['holaplex:theme:font:text'],
        },
      },
      meta: {
        favicon: maybeCDN(
          values['holaplex:metadata:favicon:url'] || '/favicon-16x16.png',
        ),
        title:
          values['holaplex:metadata:page:title'] ||
          `Holaplex - ${subdomain} | NFT Marketplace`,
        description:
          values['holaplex:metadata:page:description'] ||
          'A NFT marketplace generated by Holaplex',
      },
    };
    return storefront;
  } catch (err: any) {
    console.error(err);
    return null;
  }
};

export const getStorefront = async (
  subdomain: string,
): Promise<Storefront | undefined> => {
  let cached: Storefront | undefined = undefined;
  const redisClientOptions: RedisClientOptions<RedisModules, RedisScripts> = {
    url: REDIS_URL,
  };

  if (REDIS_TLS_ENABLED) {
    redisClientOptions.socket = {
      tls: true,
      rejectUnauthorized: false,
    };
  }

  const client = createClient(redisClientOptions);

  await client.connect();

  const [storefront, timestamp] = await Promise.all([
    client.get(subdomain),
    client.get(`${subdomain}-timestamp`),
  ]);

  if (storefront) {
    cached = JSON.parse(storefront);
  }

  const now = moment();
  const lastSavedAt = moment(timestamp);

  const duration = moment.duration(now.diff(lastSavedAt)).as('minutes');

  if (duration < 2 && cached) {
    await client.quit();
    return cached;
  }

  // @ts-ignore
  const source = await fetchFromSource(subdomain, client);

  if (source) {
    await client
      .multi()
      .set(subdomain, JSON.stringify(source))
      .set(`${subdomain}-timestamp`, now.format())
      .exec();

    await client.quit();
    return source;
  }

  await client.quit();

  return cached;
};
