name: Install Rust

inputs:
  toolchain:
    description: The Rust version to use, default env.RUST_TOOLCHAIN
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Rust Stable
      id: rust_toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ inputs.toolchain }} 
          override: true
          profile: minimal
          components: rustfmt, clippy

    - name: Add Cargo bin to Path 
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Rust install 
      run: |
        echo "Verifying rust '${{ inputs.toolchain }}' ..."
        rustc --version
        cargo --version
        cargo clippy --version
        rustfmt --version
      shell: bash

    - uses: actions/cache@v2
      id: cache-stable-rust-installs-and-builds
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./rust/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ steps.rust_toolchain.outputs.rustc_hash }}
