blank_issues_enabled: false
contact_links:
  - name: Metaplex Docs
    url: https://docs.metaplex.com
    about: Please check our docs if you haven't already
  - name: Discord server
    url: https://discord.gg/metaplex
    about: Please visit our Discord server for questions and support requests.
