export const nftActivityTable = [
  {
    id: 0,
    event: 'Sale',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Sale',
    price: '◎ .09',
    from: 'brian-adams',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'men-at-work',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'kylie-minogue',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'sia',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'username-with-very-long-event',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
  {
    id: 0,
    event: 'Transfer',
    price: '◎ .09',
    from: 'elon-musk',
    to: 'kasun.peiris',
    time: '8 days ago',
  },
];
