export const unmapped: any = {
  background: [
    ['Bamboo green', 753, 'Less common'],
    ['Banana yellow ', 750, 'Less common'],
    ['Belly pink ', 375, 'Uncommon'],
    ['Royal purple ', 375, 'Uncommon'],
    ['Blood red ', 93, 'Rare'],
    ['Mango orange ', 93, 'Rare'],
    ['Beach gradient ', 93, 'Rare'],
    ['Clouds ', 27, 'Very rare'],
    ['Stars ', 7, 'Very rare'],
    ['Solana gradient ', 1, 'Über rare'],
  ],
  body: [
    ['Black', 753, 'Less common'],
    ['Grey', 750, 'Less common'],
    ['Brown', 375, 'Uncommon'],
    ['Blonde', 375, 'Uncommon'],
    ['Albino', 93, 'Rare'],
    ['Green', 93, 'Rare'],
    ['Silver', 27, 'Very rare'],
    ['Gold', 27, 'Very rare'],
    ['Ice', 7, 'Über rare'],
  ],
  sign: [
    ['Aries', 2500 / 12],
    ['Taurus', 2500 / 12],
    ['Gemini', 2500 / 12],
    ['Cancer', 2500 / 12],
    ['Leo', 2500 / 12],
    ['Virgo', 2500 / 12],
    ['Libra', 2500 / 12],
    ['Scorpio', 2500 / 12],
    ['Sagittarius', 2500 / 12],
    ['Capricorn', 2500 / 12],
    ['Aquarius', 2500 / 12],
    ['Pisces', 2500 / 12],
  ],
  clan: [
    ['Harambe', 2500 / 10],
    ['Digit', 2500 / 10],
    ['Koko', 2500 / 10],
    ['Gargantua', 2500 / 10],
    ['Shabani', 2500 / 10],
    ['Titus', 2500 / 10],
    ['Binti Jua', 2500 / 10],
    ['Bobo', 2500 / 10],
    ['Colo', 2500 / 10],
    ['Michael', 2500 / 10],
  ],
  eyes: [
    ['Brown', 750, 'Less common'],
    ['Green', 375, 'Uncommon'],
    ['Blue', 375, 'Uncommon'],
    ['Blue (winking)', 375, 'Uncommon'],
    ['Glasses', 175, 'Uncommon'],
    ['Sunglasses', 92, 'Rare'],
    ['Dead eyes', 92, 'Rare'],
    ['Gems', 91, 'Rare'],
    ['Lit Pythons', 92, 'Rare'],
    ['Insect eyes', 25, 'Very rare'],
    ['Heart eyes', 25, 'Very rare'],
    ['Psychedelic eyes', 25, 'Very rare'],
    ['Hypno eyes', 25, 'Very rare'],
    ['Alien', 8, 'Über rare'],
  ],
  mouth: [
    ['None', 750, 'Less Common'],
    ['Teeth', 750, 'Less Common'],
    ['Red lipstick', 375, 'Uncommon'],
    ['Tongue out', 375, 'Uncommon'],
    ['Black lipstick', 94, 'Rare'],
    ['Banana', 93, 'Rare'],
    ['Rose', 25, 'Very rare'],
    ['Gold teeth', 25, 'Very rare'],
    ['Bubble pipe ', 13, 'Über rare'],
  ],
  accessories: [
    ['None', 1164, 'Common'],
    ['Nose ring silver', 750, 'Less common'],
    ['Septum ring', 375, 'Uncommon'],
    ['Nose ring gold', 93, 'Rare'],
    ['Septum ring silver', 93, 'Rare'],
    ['Earring gold', 25, 'Very rare'],
  ],
  clothes: [
    ['None', 750, 'Less common'],
    ['White T-Shirt', 375, 'Uncommon'],
    ['Football Jersey', 375, 'Uncommon'],
    ['String vest', 375, 'Uncommon'],
    ['Soccer Jersey', 175, 'Uncommon'],
    ['Prom dress', 92, 'Rare'],
    ['Blue Tuxedo', 92, 'Rare'],
    ['Bra', 91, 'Rare'],
    ['Plaid shirt', 91, 'Rare'],
    ['Solana T-Shirt', 25, 'Very rare'],
    ['Corset', 25, 'Very rare'],
    ['Cape', 25, 'Very rare'],
    ['King robe', 8, 'Über rare'],
  ],
  head: [
    ['None', 742, 'Less common'],
    ['Short hair', 375, 'Uncommon'],
    ['Long straight hair', 375, 'Uncommon'],
    ['Long wavy brown', 375, 'Uncommon'],
    ['Blonde Bob', 175, 'Uncommon'],
    ['Beanie', 92, 'Rare'],
    ['Balding', 92, 'Rare'],
    ['Fauxhawk', 91, 'Rare'],
    ['Afro', 92, 'Rare'],
    ['Pink Bob', 25, 'Very rare'],
    ['Long straight blue', 25, 'Very rare'],
    ['Mohawk', 25, 'Very rare'],
    ['Visor', 8, 'Über rare'],
    ['Top hat', 8, 'Über rare'],
  ],
};

export const attributes = Object.keys(unmapped).reduce((acc, key) => {
  const list = unmapped[key].map((arr: any) => {
    return [
      arr[0],
      Math.round((1 / (2500 / 100 / +arr[1])) * 100) / 100,
      arr[2],
    ];
  });
  acc[key] = list;
  return acc;
}, {} as { [key: string]: any[] });
